### ISSUE TITLE
Race condition with GC in constructors for DoubleGauge and LongGauge

### ISSUE THREAD

**Issue by nedgar** [Netflix/servo#359]
DoubleGauge and LongGauge are subclasses of NumberGauge, which uses a WeakReference to the Number. The subclass constructors then get the Number using getBackingNumber() and store it as a strong reference, so it won't be GCed. However, if the GC runs between the call to super and the call to getBackingNumber(), the result will likely be null, causing NPEs in the methods that reference number.

I was able to demonstrate this in the debugger by setting a breakpoint where the number field is assigned, and forcing a GC. The weak ref gets cleared.

The most likely impact is to StatsMonitor, which uses both DoubleGauge and LongGauge.
Seen in v0.10.0, but the code is the same in the latest.

**Comment by nedgar** [comment]
A simple fix would be to assign the field in the super statement, e.g.

    public LongGauge(MonitorConfig config) {
        super(config, number = new AtomicLong(0L));
    }

**Comment by dmuino** [comment]
Thanks for the report. We use a WeakReference in NumberGauge so we can have code like:

```java
final class Servo {
  private static final ConcurrentMap<MonitorConfig, NumberGauge> GAUGES = new ConcurrentHashMap<>();

 @SuppressWarnings("unchecked")
  public static <T extends Number> T getNumberGauge(MonitorConfig config, T number) {
    NumberGauge v = GAUGES.get(config);
    if (v != null) {
      return (T) v.getValue(0);
    } else {
      NumberGauge gauge = new NumberGauge(config, number);
      NumberGauge prev = GAUGES.putIfAbsent(config, gauge);
      if (prev != null) {
        return (T) prev.getValue(0);
      } else {
        DefaultMonitorRegistry.getInstance().register(gauge);
        return (T) gauge.getValue(0);
      }
    }
  }

  public static <T extends Number> T getNumberGauge(String name, T number) {
    return getNumberGauge(MonitorConfig.builder(name).build(), number);
  }
```

And then use the above code as follows:

```java

class SomethingThatWillBeGC {
  private final AtomicLong foo;
  SomethingThatWillBeGC() {
    foo = Servo.getNumberGauge("foo", new AtomicLong(100L));
  }

  void someMethod() {
    foo.set(42L);
  }
}
```

The idea is that when foo gets collected we can take appropriate action. Currently we just report NaN, but it should be possible to unregister the monitor completely.

DoubleGauge and LongGauge predate NumberGauge, and now they really don't serve a particularly useful role. Brian H. while reviewing the PR suggested we deprecate them and I'm planning to do that in the near future.

**Comment by qixiaobo** [comment]
the same problem meet!
```plain
java.lang.NullPointerException: null
	at com.netflix.servo.monitor.DoubleGauge.set(DoubleGauge.java:40)
	at org.springframework.cloud.netflix.metrics.servo.ServoMetricServices.submit(ServoMetricServices.java:142)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.submitToGauge(MetricsFilter.java:217)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.submitMetrics(MetricsFilter.java:193)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.recordMetrics(MetricsFilter.java:143)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:116)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at com.alibaba.csp.sentinel.adapter.servlet.CommonFilter.doFilter(CommonFilter.java:91)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:332)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by brharrington** [comment]
I would recommend double checking you have the latest version. Also note, this project is [deprecated](https://github.com/Netflix/servo/blob/master/README.md#deprecated) so even if it is a current issue it is unlikely we will investigate or fix.
